import "@/styles/globals.css";
// @ts-ignore
import { Metadata } from "next";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";
import { type ReactNode, Suspense } from "react";
import { connection } from "next/server";

export const metadata: Metadata = {
  title: "Wasteland Webview",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }]
};

async function UTSSR() {
  await connection();
  return <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />;
}

export default function RootLayout({
                                     children
                                   }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body>
      <Suspense> <UTSSR /> </Suspense>
      {children}
    </body>
    </html>
  );
}
